name: CI/CD with Feature Flags

on:
  push:
    branches:
      - main
      - 'feature/*'
      - 'fix/*'
      - 'bugfix/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install flask

      - name: Run tests
        run: pytest

  deploy-staging:
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/heads/feature/') || startsWith(github.ref, 'refs/heads/fix/')
    steps:
      - name: Deploy to Staging
        run: ./deploy_staging.sh

  deploy-production:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to Production
        run: ./deploy_production.sh

      - name: Enable Feature Flag
        run: |
          curl -X POST "https://api.flagsmith.com/environments/<env_id>/flags/FEATURE_A" -H "Authorization: Bearer <api-key>" -d '{"enabled": true}'
